name: BiliDanmuVoter
version: 1.0.0
main: ink.imimi.BiliDanmuVoter.BiliDanmuVoter
load: STARTUP
api-version: 1.16

commands:
  vote:
    description: Enable voting event
    usage: /<command>
    permission: BiliDanmuVoter.admin